### ISSUE TITLE
App crashes when the call is in background

### ISSUE THREAD

**Issue by EjazAmir** [Gruveo/sdk-examples-android-java#19]
I have implemented Gruveo Sdk in android application and it works fine when the activity is in foreground but it crashes as the user intentionally allows the app to go in background. I'm attaching the crash logs
[crash log.docx](https://github.com/Gruveo/sdk-examples-android-java/files/4598768/crash.log.docx)

**Comment by akkewood** [comment]
Hi @EjazAmir 
Could you please check your manifest file?
Did you add there next lines:
` <activity
            android:name="com.gruveo.sdk.ui.CallActivity"
            android:configChanges="orientation|screenSize"/>`
?
Please see example here https://github.com/Gruveo/sdk-examples-android-java/blob/master/app/src/main/AndroidManifest.xml

**Comment by EjazAmir** [comment]
yes, already added. But still app crashes when call goes in background

**Comment by akkewood** [comment]
Which sdk version do you use?
Also could you please check it with sample app from this repository? Does this crash reproduce with sample app on your device?

**Comment by akkewood** [comment]
@EjazAmir Could you please try to update sdk version to 0.7.6?
I think we've managed to fix it in latest (0.7.6) version

**Comment by EjazAmir** [comment]
Upgraded the sdk version to 0.7.6. Now not able to make a call, app crashes with following crash logs.

===========================================================


2020-05-11 16:04:13.527 12366-12366/com.shifaam.patient E/UncaughtException: java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
        at org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
        at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:3)
        at com.gruveo.sdk.api.peerConnection.PeerConnectionClient.createPeerConnectionFactoryInternal(PeerConnectionClient.kt:16)
        at com.gruveo.sdk.api.peerConnection.PeerConnectionClient.createPeerConnectionFactory(PeerConnectionClient.kt:15)
        at com.gruveo.sdk.model.PeerController.onCreate(PeerController.kt:4)
        at com.gruveo.sdk.model.PeerController.onCreate$default(PeerController.kt:1)
        at com.gruveo.sdk.ui.CallContainerFragment.permissionsHandled(CallContainerFragment.kt:15)
        at com.gruveo.sdk.ui.CallContainerFragment.audioPermissionGranted(CallContainerFragment.kt:8)
        at com.gruveo.sdk.ui.CallContainerFragment.access$audioPermissionGranted(CallContainerFragment.kt:1)
        at com.gruveo.sdk.ui.CallContainerFragment$checkConnectionStatus$1.invoke(CallContainerFragment.kt:2)
        at com.gruveo.sdk.ui.CallContainerFragment$checkConnectionStatus$1.invoke(CallContainerFragment.kt:1)
        at com.gruveo.sdk.ui.CallContainerFragment.handlePermission(CallContainerFragment.kt:3)
        at com.gruveo.sdk.ui.CallContainerFragment.checkConnectionStatus(CallContainerFragment.kt:1)
        at com.gruveo.sdk.ui.CallContainerFragment.initCall(CallContainerFragment.kt:31)
        at com.gruveo.sdk.ui.CallContainerFragment.fragmentCreated$sdk_release(CallContainerFragment.kt:19)
        at com.gruveo.sdk.fragments.CallFragment.initFragment(CallFragment.kt:30)
        at com.gruveo.sdk.fragments.CallFragment.onViewCreated(CallFragment.kt:8)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:434)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
        at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:259)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23454)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:1000)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
2020-05-11 16:04:13.528 12366-12366/com.shifaam.patient E/UncaughtException:     at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:847)
        at android.view.View.measure(View.java:23454)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2954)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1753)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2041)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
        at android.view.Choreographer.doFrame(Choreographer.java:812)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by akkewood** [comment]
Could you please do 'project clean' and 'project rebuild' in your android studio?

**Comment by EjazAmir** [comment]
Yeah that worked. Now having another issue, when the app goes to foreground from background the call options (video view, call buttons) didn't visible. 

Attaching the screen shot for reference.

![96519325_232878778132787_6836963210763960320_n](https://user-images.githubusercontent.com/25684301/81650277-14c2f300-944b-11ea-928f-cf425168014b.jpg)

**Comment by akkewood** [comment]
Please show how you initiate gruveo call

**Comment by EjazAmir** [comment]
Here's the code to init the call,


private fun initCall(videoCall: Boolean, roomCode : String) {
        back?.gone()
        val otherExtras = Bundle().apply {
            putBoolean(Gruveo.GRV_EXTRA_VIBRATE_IN_CHAT, false)
            putBoolean(Gruveo.GRV_EXTRA_DISABLE_CHAT, false)
        }

        val result = Gruveo.Builder(OnlineActivity@this)
                .viewContainer(R.id.gruveo_container)
                .callCode(roomCode)
                .videoCall(videoCall)
                .clientId(Constants.ClientId)
                .requestCode(REQUEST_CALL)
//                .secureDisplay(true)
                .otherExtras(otherExtras)
                .eventsListener(eventsListener)

                .build()


        when (result) {
            Gruveo.GRV_INIT_MISSING_CALL_CODE -> { MvpStarterApplication.appUtils.toastMessage("GRV_INIT_MISSING_CALL_CODE")}
            Gruveo.GRV_INIT_INVALID_CALL_CODE -> { MvpStarterApplication.appUtils.toastMessage("GRV_INIT_INVALID_CALL_CODE")}
            Gruveo.GRV_INIT_MISSING_CLIENT_ID -> { MvpStarterApplication.appUtils.toastMessage("GRV_INIT_MISSING_CLIENT_ID")}
            Gruveo.GRV_INIT_OFFLINE -> { MvpStarterApplication.appUtils.toastMessage("GRV_INIT_OFFLINE")}
            else -> { MvpStarterApplication.appUtils.toastMessage(result)}
        }
    }

**Comment by akkewood** [comment]
Does you show call in full screen?
If you show it in full screen you should remove the line 
` .viewContainer(R.id.gruveo_container)`
Also I noticed on your screenshot some kind of rectangle in the right bottom corner. Gruveo sdk doesn't have such elements. What is it?

Also did you try to reproduce it with our sample app?
I cannot reproduce you bug right know:
My steps for reproduce:
1. Initiate call
2. Move app to backgroun
3. Return app from background

With this steps issue doesn't reproduce on my devices

**Comment by EjazAmir** [comment]
No, I'm showing the call view in a container.

That rectangle is created by me, to allow users to go to full screen view or to shrink back to the normal size.

I tried your sample app, from code and found that it also kills the call when the app goes to background.

**Comment by akkewood** [comment]
In case when you try to initiate call, waiting for answer and move the app to background - sdk stops current call. This is intentional behavior.

**Comment by EjazAmir** [comment]
Alright,
But we have a different case, user initiate call and waiting for the doctor to answer the call, until then the patient is in queue list so we are playing waiting sound for user. Now in this case if user allows the app to go to background and then move the app to foreground the calls teen becomes empty, no control options visible as you can see in above image.

**Comment by artmatsak** [comment]
@EjazAmir You need to detect returning from background and re-initiate the call in this case.
