### ISSUE TITLE
No implementation found for void org.webrtc.PeerConnectionFactory.initializeFieldTrials(java.lang.String)

### ISSUE THREAD

**Issue by dannyboy46** [Gruveo/sdk-examples-android-java#2]
Hi, I want to implement Gruveo as my video call function, but when I called the initCall method (recording to the java sample), the app crashed. But it's not crash on my Samsung device, Lolipop version. Do you have any idea why this issue occured? Thanks

`E/art: No implementation found for void org.webrtc.PeerConnectionFactory.initializeFieldTrials(java.lang.String) (tried Java_org_webrtc_PeerConnectionFactory_initializeFieldTrials and Java_org_webrtc_PeerConnectionFactory_initializeFieldTrials__Ljava_lang_String_2)
        D/AndroidRuntime: Shutting down VM
        E/CrashlyticsCore: Tried to write a fatal exception while no session was open.
        E/AndroidRuntime: FATAL EXCEPTION: main
        java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.initializeFieldTrials(java.lang.String) (tried Java_org_webrtc_PeerConnectionFactory_initializeFieldTrials and Java_org_webrtc_PeerConnectionFactory_initializeFieldTrials__Ljava_lang_String_2)
        at org.webrtc.PeerConnectionFactory.initializeFieldTrials(Native Method)
        at com.gruveo.sdk.api.peerConnection.PeerConnectionClient.createPeerConnectionFactoryInternal(PeerConnectionClient.kt:194)
        at com.gruveo.sdk.api.peerConnection.PeerConnectionClient.createPeerConnectionFactory(PeerConnectionClient.kt:111)
        at com.gruveo.sdk.model.PeerController.onCreate(PeerController.kt:23)
        at com.gruveo.sdk.model.PeerController.onCreate$default(PeerController.kt:19)
        at com.gruveo.sdk.ui.CallActivity.permissionsHandled(CallActivity.kt:223)
        at com.gruveo.sdk.ui.CallActivity.access$permissionsHandled(CallActivity.kt:67)
        at com.gruveo.sdk.ui.CallActivity$audioPermissionGranted$1.invoke(CallActivity.kt:204)
        at com.gruveo.sdk.ui.CallActivity$audioPermissionGranted$1.invoke(CallActivity.kt:67)
        at com.gruveo.sdk.ui.CallActivity.handlePermission(CallActivity.kt:1258)
        at com.gruveo.sdk.ui.CallActivity.audioPermissionGranted(CallActivity.kt:202)
        at com.gruveo.sdk.ui.CallActivity.access$audioPermissionGranted(CallActivity.kt:67)
        at com.gruveo.sdk.ui.CallActivity$checkConnectionStatus$1.invoke(CallActivity.kt:181)
        at com.gruveo.sdk.ui.CallActivity$checkConnectionStatus$1.invoke(CallActivity.kt:67)
        at com.gruveo.sdk.ui.CallActivity.handlePermission(CallActivity.kt:1258)
        at com.gruveo.sdk.ui.CallActivity.checkConnectionStatus(CallActivity.kt:179)
        at com.gruveo.sdk.ui.CallActivity.initCall(CallActivity.kt:254)
        at com.gruveo.sdk.ui.CallActivity.fragmentCreated$sdk_release(CallActivity.kt:1180)
        at com.gruveo.sdk.fragments.CallFragment.initFragment(CallFragment.kt:177)
        at com.gruveo.sdk.fragments.CallFragment.onViewCreated(CallFragment.kt:141)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:20084)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
        at android.view.View.measure(View.java:20084)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
        at android.view.View.measure(View.java:20084)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
        at android.view.View.measure(View.java:20084)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1705)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:797)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
        at android.view.View.measure(View.java:20084)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6282)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:214)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:714)
        at android.view.View.measure(View.java:20084)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2627)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1577)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1846)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6960)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
        at android.view.Choreographer.doCallbacks(Choreographer.java:709)
        at android.view.Choreographer.doFrame(Choreographer.java:644)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:208)
        at android.app.ActivityThread.main(ActivityThread.java:6267)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)`

**Comment by tibbi** [comment]
Hey, do you have proguard enabled? Does the official Gruveo app work fine to you? Thanks

**Comment by dannyboy46** [comment]
No, I disabled the proguard. Will there be any issue if I enable the proguard?
I tried the sample project, and it works fine on both devices. But what I did on my project was just copying the MainActivity from your sample, and setting the gradle according the sample. Do you have any Idea what's wrong, since it's running on the device but not on the other. Thanks


UPDATE
Today I just did a research that, if I run it on a 32bit device, it works, but not in 64bit device, so I added
ndk {abiFilters "armeabi", "armeabi-v7a", "x86", "mips"}, and then the gruveo works fine on both. So I will close the issue now. Thanks for your time, may this help some people.

**Comment by tibbi** [comment]
Alright cool, thanks.

**Comment by codecsand** [comment]
I had the same problem.
I didn't enabled proguard.
I didn't add any ndk abiFilters

I solved it by **remove AndroidLame library**.
https://github.com/naman14/TAndroidLame/tree/master/androidlame
there was a conflict between 2 these libraries.

I Hope this help some one.
Thanks.

**Comment by jubole97** [comment]
> No, desactivé el Proguard. ¿Habrá algún problema si habilito el proguard?
> Probé el proyecto de muestra y funciona bien en ambos dispositivos. Pero lo que hice en mi proyecto fue simplemente copiar MainActivity de su muestra y configurar el gradle de acuerdo con la muestra. ¿Tiene alguna idea de lo que está mal, ya que se está ejecutando en el dispositivo pero no en el otro? Gracias
> 
> ACTUALIZACIÓN
> Hoy acabo de investigar que, si lo ejecuto en un dispositivo de 32 bits, funciona, pero no en un dispositivo de 64 bits, así que agregué
> ndk {abiFilters "armeabi", "armeabi-v7a", "x86", "mips" }, y luego el gruveo funciona bien en ambos. Así que cerraré el tema ahora. Gracias por tu tiempo, que esto ayude a algunas personas.

En dónde se habilita el ndk=?

**Comment by prateekpros** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libLibvpxVp9Decoder.so" not found
at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
at java.lang.System.loadLibrary(System.java:1661)
at com.example.videocall.MeetingActivity.<clinit>(MeetingActivity.java:21)
at java.lang.Class.newInstance(Native Method)
at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
at android.app.Instrumentation.newActivity(Instrumentation.java:1378)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by prateekpros** [comment]
java.lang.UnsatisfiedLinkError: No implementation found for boolean org.webrtc.LibvpxVp9Decoder.nativeIsSupported() (tried Java_org_webrtc_LibvpxVp9Decoder_nativeIsSupported and Java_org_webrtc_LibvpxVp9Decoder_nativeIsSupported__) - is the library loaded, e.g. System.loadLibrary?
at org.webrtc.LibvpxVp9Decoder.nativeIsSupported(Native Method)
at org.webrtc.SoftwareVideoDecoderFactory.supportedCodecs(SoftwareVideoDecoderFactory.java:48)
at org.webrtc.SoftwareVideoDecoderFactory.getSupportedCodecs(SoftwareVideoDecoderFactory.java:41)
at org.webrtc.DefaultVideoDecoderFactory.getSupportedCodecs(DefaultVideoDecoderFactory.java:60)
at io.github.crow_misia.webrtc.RTCComponentFactory.createPeerConnectionFactory(RTCComponentFactory.kt:58)
at live.videosdk.rtc.android.lib.RoomClient.<init>(RoomClient.java:266)
at live.videosdk.rtc.android.VideoSDK.initMeeting(VideoSDK.java:156)
at com.example.videocall.MeetingActivity.onCreate(MeetingActivity.java:40)
at android.app.Activity.performCreate(Activity.java:8595)
at android.app.Activity.performCreate(Activity.java:8573)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by urkeke** [comment]
@prateekpros It's not Gruveo's trace?
