### ISSUE TITLE
App crash when disconnect call.

### ISSUE THREAD

**Issue by MuhammadSajjadSaleem** [Gruveo/sdk-examples-android-java#21]
I'm using version 0.7.6. App crash when one side app disconnect for some reason and other app crash when the button press for the disconnect.

Here is Error Log
java.lang.IllegalStateException: incoming_queue_text must not be null
        at com.gruveo.sdk.fragments.CallFragment.isIncomingQueueVisible(CallFragment.kt:1)
        at com.gruveo.sdk.ui.DragLayout.getTopHeight(DragLayout.kt:25)
        at com.gruveo.sdk.ui.DragLayout.moveToPosition(DragLayout.kt:23)
        at com.gruveo.sdk.ui.DragLayout.recalculatePosition(DragLayout.kt:2)
        at com.gruveo.sdk.ui.DragLayout$refreshPreviewPosition$1.onGlobalLayout(DragLayout.kt:2)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1070)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3185)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9065)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:732)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8019)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by MuhammadSajjadSaleem** [comment]
Any update?

**Comment by artmatsak** [comment]
Sorry about the big delay, we are looking into this and will get back to you shortly.

**Comment by MuhammadSajjadSaleem** [comment]
Thanks, it's resolved after the upgrade version.
